### ISSUE TITLE
comments and test

### ISSUE THREAD

**Issue by unlucio** [namshi/node-nmconfig#1]
Hello @metanitesh and @p16 
any suggestion for me? ;)

**Comment by p16** [comment]
@unlucio  Does https://github.com/namshi/node-nm-config/blob/start/index.js#L44 means that I should have XXX.example.yml, YYY.example.yml, etc in my config folder?

**Comment by p16** [comment]
@unlucio add test.yml https://github.com/namshi/node-nm-config/blob/start/index.js#L12 :P

**Comment by unlucio** [comment]
@p16 it's ensured only the file you ask to be ensured

**Comment by unlucio** [comment]
test? :)
